### ISSUE TITLE
problem z polskimi znaczkami

### ISSUE THREAD

**Issue by tomeks86** [Hoymm/OX#46]
może trzeba będzie skorzystać ze wskazówki:
https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle
native2ascii

**Comment by tomeks86** [comment]
tłumaczenie na ascii pomaga:
native2ascii -encoding UTF-8 language_pl_PL.properties language_pl_PL.properties
operacja odwotna:
native2ascii -encoding UTF-8 language_pl_PL.properties language_pl_PL.properties -reverse
^^

**Comment by Hoymm** [comment]
Dzięki wielki !!!

**Comment by Hoymm** [comment]
Naprawione
